Models/Parameter.cs
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WASA_EMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Parameter
    {
        public int ParameterID { get; set; }
        public string ParameterName { get; set; }
        public string ParameterUnit { get; set; }
        public int ParameterOrder { get; set; }
        public string AggFunc { get; set; }
        public Nullable<double> ParameterScale { get; set; }
    }
}

Controllers/ParameterController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.SqlClient;
using WASA_EMS.Models;
using System.Data.Entity;
using System.Net;
using System.Data;

namespace WASA_EMS.Controllers
{
    public class ParameterController : Controller
    {
        WASA_EMS_Entities db = new WASA_EMS_Entities();

        // GET: Parameter/Index
        public ActionResult Index()
        {
            int c_id = Convert.ToInt32(Session["CompanyID"]);
            ViewBag.parameterList = db.tblParameters.AsEnumerable().Where(item => item.CompanyID == c_id);
            return View();
        }

        /*
        // GET: Parameter/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tblParameter tblParameter = db.tblParameters.Find(id);
            if (tblParameter == null)
            {
                return HttpNotFound();
            }
            return View(tblParameter);
        }
        */

        // GET: Parameter/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Parameter/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ParameterID,ParameterName,ParameterOrder,Mainformula")] tblParameter tblparameter)
        {
            int c_id = Convert.ToInt32(Session["CompanyID"]);
            if (ModelState.IsValid)
            {
                tblparameter.CompanyID = c_id;
                db.tblParameters.Add(tblparameter);
                db.SaveChanges();
                DisplaySuccessMessage("Has append a tblParameter record");
                return RedirectToAction("Index");
            }

            DisplayErrorMessage();
            return View(tblparameter);
        }

        // GET: Parameter/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tblParameter tblparameter = db.tblParameters.Find(id);
            if (tblparameter == null)
            {
                return HttpNotFound();
            }

            return View(tblparameter);
        }

        // POST: Parameter/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ParameterID,ParameterName,ParameterOrder,Mainformula")] tblParameter tblparameter)
        {
            int c_id = Convert.ToInt32(Session["CompanyID"]);
            if (ModelState.IsValid)
            {
                tblparameter.CompanyID = c_id;
                db.Entry(tblparameter).State = EntityState.Modified;
                db.SaveChanges();
                DisplaySuccessMessage("Has update a tblParameter record");
                return RedirectToAction("Index");
            }
            DisplayErrorMessage();
            return View(tblparameter);
        }

        // GET: Parameter/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tblParameter tblparameter = db.tblParameters.Find(id);
            if (tblparameter == null)
            {
                return HttpNotFound();
            }
            return View(tblparameter);
        }

        // POST: Parameter/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            tblParameter tblparameter = db.tblParameters.Find(id);
            db.tblParameters.Remove(tblparameter);
            db.SaveChanges();
            DisplaySuccessMessage("Has delete a tblParameter record");
            return RedirectToAction("Index");
        }

        private void DisplaySuccessMessage(string msgText)
        {
            TempData["SuccessMessage"] = msgText;
        }

        private void DisplayErrorMessage()
        {
            TempData["ErrorMessage"] = "Save changes was unsuccessful.";
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/Parameter/Create.cshtml
@model WASA_EMS.Models.tblParameter

@{
    ViewBag.Title = "Create";
}

@*@if (string.IsNullOrEmpty(Session["CompanyID"].ToString() as string))
    {
        Response.Redirect("~/Account/LogOn");
    }*@
@*@{ string c_ID = Session["CompanyID"].ToString();}

    @if (c_ID == null)
    {
        Response.Redirect("~/Account/LogOn");
    }*@
<script src="@Url.Content("~/Scripts/jquery-1.7.2.min.js")" type="text/javascript"></script>
<script src="//code.jquery.com/ui/1.10.4/jquery-ui.js"></script>
<script src="@Url.Content("~/Scripts/Highcharts-2.2.1/js/highcharts.src.js")" type="text/javascript"></script>
<script src="~/Scripts/js/date-picker/date.js"></script>


<div class="main">

    <div class="container"  style="background-color:white; padding:20px 40px; opacity:0.9">
        <div class="row">

            <div class="span12">

                <div class="widget stacked">

                    <div class="widget-header">
                        <h3>Create New Parameter</h3>
                    </div> <!-- /widget-header -->

                    <br />

                    <div class="widget-content">

                        @using (Html.BeginForm())
                        {
                            @Html.AntiForgeryToken()



                            <div class="form-horizontal">
                                <h4>New Parameter</h4>
                                <hr />
                                @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                                @*@Html.Partial("EditForm")*@


                                <div class="form-group">
                                    <div style="float:left; margin-right:10px">
                                        @Html.LabelFor(model => model.ParameterName, htmlAttributes: new { @class = "control-label col-md-2" })
                                    </div>


                                    <div class="col-md-10" style="margin-left:10px">
                                        @Html.EditorFor(model => model.ParameterName, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.ParameterName, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <br />

                                <div class="form-group">
                                    <div style="float:left; margin-right:10px">
                                        @Html.LabelFor(model => model.ParameterOrder, htmlAttributes: new { @class = "control-label col-md-2" })
                                    </div>
                                    <div class="col-md-10">
                                        @Html.EditorFor(model => model.ParameterOrder, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.ParameterOrder, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <br />

                                <div class="form-group">
                                    <div style="float:left; margin-right:10px">
                                        @Html.LabelFor(model => model.Mainformula, htmlAttributes: new { @class = "control-label col-md-2" })
                                    </div>
                                    <div class="col-md-10">
                                        @Html.EditorFor(model => model.Mainformula, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.Mainformula, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <br />

                                <div class="form-group">
                                    <div class="col-md-offset-2 col-md-10">
                                        <input type="submit" value="Create" class="btn btn-primary" />
                                    </div>
                                </div>

                                <br />

                                <div class="widget-header">
                                    <b style="text-align:left; vertical-align:central; text-align; font-size:12px; margin-left:10px">
                                        @Html.ActionLink("Back to Parameters List", "Index")
                                    </b>
                                </div>

                            </div>
                        }

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>








@*@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}*@

Views/Parameter/Edit.cshtml
@model WASA_EMS.Models.tblParameter
@{
    ViewBag.Title = "Edit";
}
@*@if (string.IsNullOrEmpty(Session["CompanyID"].ToString() as string))
{
    Response.Redirect("~/Account/LogOn");
}*@
@*@{ string c_ID = Session["CompanyID"].ToString();}

    @if (c_ID == null)
    {
        Response.Redirect("~/Account/LogOn");
    }*@
<script src="@Url.Content("~/Scripts/jquery-1.7.2.min.js")" type="text/javascript"></script>
<script src="//code.jquery.com/ui/1.10.4/jquery-ui.js"></script>
<script src="@Url.Content("~/Scripts/Highcharts-2.2.1/js/highcharts.src.js")" type="text/javascript"></script>
<script src="~/Scripts/js/date-picker/date.js"></script>


<div class="main">

    <div class="container" style="background-color:white; padding:20px 40px; opacity:0.9">
        <div class="row">

            <div class="span12">

                <div class="widget stacked">

                    <div class="widget-header">
                        <h3>Parameter</h3>
                    </div> <!-- /widget-header -->

                    <br />

                    <div class="widget-content">

                        @using (Html.BeginForm())
                        {
                            @Html.AntiForgeryToken()

                            <div class="form-horizontal">
                                <h4>Edit</h4>
                                <hr />
                                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                                @Html.Partial("EditForm")

                                <br />

                                <div class="form-group">
                                    <div class="col-md-offset-2 col-md-10">
                                        <div style="float:left; margin-right:10px">
                                            <input type="submit" class="btn btn-primary" value="Save" />
                                        </div>
                                        <div style="float:left">
                                            <input type="button" class="btn btn-default" data-toggle="modal" data-target="#myModal" value="Delete" />
                                        </div>
                                    </div>
                                </div>
                                <br />
                            </div>
                        }

                        <div class="widget-header">
                            <b style="text-align:left; vertical-align:central; text-align; font-size:12px; margin-left:10px">
                                @Html.ActionLink("Back to Parameters List", "Index")
                            </b>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>



@*@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Parameter</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.Partial("EditForm")
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" class="btn btn-primary" value="Save" />
                <input type="button" class="btn btn-default" data-toggle="modal" data-target="#myModal" value="Delete" />
            </div>
        </div>
    </div>
}*@



<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title" id="myModalLabel">Warning !!</h4>
            </div>
            <div class="modal-body">
                Are you sure you want to delete this item ?
            </div>
            <div class="modal-footer">
                @using (Html.BeginForm("Delete", "Parameter", new { id=Model.ParameterID}))
                {
                    @Html.AntiForgeryToken()
                    <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                    <button type="submit" class="btn btn-warning">Delete</button>
                }
            </div>
        </div>
    </div>
</div>

@*@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}*@

Views/Parameter/EditForm.cshtml
@model WASA_EMS.Models.tblParameter

@*@if (string.IsNullOrEmpty(Session["CompanyID"].ToString() as string))
    {
        Response.Redirect("~/Account/LogOn");
    }*@
@*@{ string c_ID = Session["CompanyID"].ToString();}

    @if (c_ID == null)
    {
        Response.Redirect("~/Account/LogOn");
    }*@
@using (Html.BeginForm())
{
    @*@Html.AntiForgeryToken()*@

    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    @Html.HiddenFor(model => model.ParameterID)


    <div class="form-group">
        <div style="float:left; margin-right:10px">
            @Html.LabelFor(model => model.ParameterName, htmlAttributes: new { @class = "control-label col-md-2" })
        </div>
        <div class="col-md-10">
            @Html.EditorFor(model => model.ParameterName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.ParameterName, "", new { @class = "text-danger" })
        </div>
    </div>

        <br />

        <div class="form-group">
            <div style="float:left; margin-right:10px">
                @Html.LabelFor(model => model.ParameterOrder, htmlAttributes: new { @class = "control-label col-md-2" })
            </div>
            <div class="col-md-10">
                @Html.EditorFor(model => model.ParameterOrder, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ParameterOrder, "", new { @class = "text-danger" })
            </div>
        </div>

        <br />

        <div class="form-group">
            <div style="float:left; margin-right:10px">
                @Html.LabelFor(model => model.Mainformula, htmlAttributes: new { @class = "control-label col-md-2" })
            </div>
            <div class="col-md-10">
                @Html.EditorFor(model => model.Mainformula, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Mainformula, "", new { @class = "text-danger" })
            </div>
        </div>
}

Views/Parameter/Index.cshtml
@model IEnumerable<WASA_EMS.Models.tblParameter>

@{
    ViewBag.Title = "Index";
}
@*@if (string.IsNullOrEmpty(Session["CompanyID"].ToString() as string))
{
    Response.Redirect("~/Account/LogOn");
}*@
@*@{ string c_ID = Session["CompanyID"].ToString();}

    @if (c_ID == null)
    {
        Response.Redirect("~/Account/LogOn");
    }*@
<script src="@Url.Content("~/Scripts/jquery-1.7.2.min.js")" type="text/javascript"></script>
<script src="//code.jquery.com/ui/1.10.4/jquery-ui.js"></script>
<script src="@Url.Content("~/Scripts/Highcharts-2.2.1/js/highcharts.src.js")" type="text/javascript"></script>
<script src="~/Scripts/js/date-picker/date.js"></script>


                      <div class="main">

                          <div class="container" style="background-color:white; padding:20px 40px; opacity:0.9">
                              <div class="row">

                                  <div class="span12">

                                      <div class="widget stacked">

                                          <div class="widget-header">
                                              <h3>Index-Parameters</h3>
                                          </div> <!-- /widget-header -->

                                          <div class="widget-content">
                                              <p>
                                                  @Html.ActionLink("Create New Parameter", "Create")
                                              </p>

                                              @*<table class="table table-bordered table-highlight ">
                                    <tr>
                                        <th>
                                            @Html.DisplayNameFor(model => model.UserName)
                                        </th>
                                        <th>
                                            @Html.DisplayNameFor(model => model.UserPassword)
                                        </th>
                                        <th></th>
                                    </tr>

                                    @foreach (var item in Model)
                                    {
                                        <tr>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.UserName)
                                            </td>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.UserPassword)
                                            </td>
                                            <td>
                                                @Html.ActionLink("Edit", "Edit", new { id = item.UserID }) |
                                                @Html.ActionLink("Details", "Details", new { id = item.UserID }) |
                                                @Html.ActionLink("Delete", "Delete", new { id = item.UserID })
                                            </td>
                                        </tr>
                                    }

                                </table>*@

                                              <table class="table table-bordered table-highlight ">
                                                  <thead>
                                                      <tr>
                                                          <td></td>
                                                          <td>Parameter</td>
                                                          <td>Parameter Order</td>
                                                          <td>Formula</td>
                                                          
                                                      </tr>

                                                  </thead>
                                                  @foreach (WASA_EMS.Models.tblParameter u in ViewBag.parameterList)
                                                  {
                                                      <tr>
                                                          <td width="10px">
                                                              @Html.ActionLink("Edit", "Edit", new { id = u.ParameterID })
                                                          </td>
                                                            <td>@u.ParameterName</td>
                                                            <td>@u.ParameterOrder</td>
                                                            <td>@u.Mainformula</td>
                                                            
                                                            
                                                      </tr>
                                                  }
                                                  <tbody>
                                                      @*@if (ViewBag.parameterList != null)
                                        {
                                            foreach (NUST_EMS.Parameter item in ViewBag.parameterList)
                                            {
                                                <tr>
                                                    <td>@item.ParameterName</td>
                                                    @foreach (NUST_EMS.Resource r in ViewBag.resourceList)
                                                    {
                                                        NUST_EMS.DBEntities db = new NUST_EMS.DBEntities();
                                                        var query = db.Database.SqlQuery<String>("select * from User").ToList();
                                                        if (query.Count > 0)
                                                        {
                                                            <td>@query[0]</td>
                                                        }
                                                        else
                                                        {
                                                            <td>-</td>
                                                        }
                                                    }

                                                </tr>
                                            }
                                        }*@
                                                  </tbody>

                                              </table>


                                          </div>
                                      </div>
                                  </div>
                              </div>
                          </div>
                      </div>




@*<h2>Index</h2>
<h4>Parameter</h4>
<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th></th>
        <th>
            @Html.DisplayNameFor(model => model.ParameterName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ParameterOrder)
        </th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.ParameterID })
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ParameterName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ParameterOrder)
        </td>

    </tr>
}

</table>*@