Controllers/SwitchController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WASA_EMS.Models;

namespace WASA_EMS.Controllers
{
    public class SwitchController : Controller
    {
        private WASA_EMS_Entities db = new WASA_EMS_Entities();

        public ActionResult Index()
        {
            if (string.IsNullOrEmpty(Convert.ToString(Session["CompanyID"])) || string.IsNullOrEmpty(Convert.ToString(Session["UserName"])))
            {
                return RedirectToAction("LogOn", "Account");
            }
            return View();
        }

        public ActionResult SetMode()
        {
            if (string.IsNullOrEmpty(Convert.ToString(Session["CompanyID"])) || string.IsNullOrEmpty(Convert.ToString(Session["UserName"])))
            {
                return RedirectToAction("LogOn", "Account");
            }
            return View();
        }

        [HttpGet]
        public PartialViewResult _ModeRecords()
        {
            var dt = new DataTable();
            var cId = Convert.ToInt32(Session["CompanyID"]);
            //var query = "select s.ID ID, r.ResourceLocation Resource, case when s.ModeManualAuto = 0 then 'Manual' ELSE 'AUTO' END as Mode, case when s.CurrentMotorOnOffStatus = 0 then   'OFF' ELSE 'ON' END as Status, case when s.CurrentMotorOnOffStatus = 0 then   'TURN ON' ELSE 'TURN OFF' END as Action from tblRemoteSensor s left join tblResource r on s.ResourceID = r.ResourceID where r.CompanyID = " + cId + "";
            var query = "";
            query += "select r.ResourceID, r.ResourceLocation, sm.Mode from tblSetMode sm ";
            query += " inner join tblResource r on sm.ResourceID = r.ResourceID ";
            using (var conn = new SqlConnection(System.Configuration.ConfigurationManager.ConnectionStrings["DefaultConnection"].ConnectionString))
            {
                try
                {
                    conn.Open();
                    var da = new SqlDataAdapter(query, conn);
                    var ds = new DataSet();
                    da.Fill(ds);
                    da.Fill(dt);
                }
                catch (Exception ex)
                {
                }
                finally
                {
                    conn.Close();
                }
            }
            return PartialView(dt);
        }

        [HttpGet]
        public PartialViewResult _SwitchRecords()
        {
            var dt = new DataTable();
            var cId = Convert.ToInt32(Session["CompanyID"]);
            using (var conn = new SqlConnection(System.Configuration.ConfigurationManager.ConnectionStrings["DefaultConnection"].ConnectionString))
            {
                try
                {
                    conn.Open();
                    string query = "";
                    query += "select TubeWellId, ResourceLocation, [Remote], PumpStatus, InsertionDateTime ";
                    query += "from(select t.TubeWellId, r.ResourceLocation, t.[Remote], t.[PumpStatus], t.[InsertionDateTime], ";
                    query += "ROW_NUMBER() OVER(PARTITION BY t.TubeWellId ORDER BY t.InsertionDateTime DESC) AS ROWNO ";
                    query += " from tblTubewellsTest t ";
                    query += " inner join tblResource r on t.TubeWellId = r.ResourceID ";
                    query += " ) AS tempTable ";
                    query += " WHERE ROWNO = 1 ";
                    query += " order by TubeWellId";

                    var sda = new SqlDataAdapter(query, conn);
                    sda.Fill(dt);
                }
                catch (Exception ex)
                {
                }
                finally
                {
                    conn.Close();
                }
            }
            return PartialView(dt);
        }

        [HttpGet]
        public PartialViewResult _SwitchRecords2()
        {
            var dt = new DataTable();
            var cId = Convert.ToInt32(Session["CompanyID"]);
            //var query = "select s.ID ID, r.ResourceLocation Resource, case when s.ModeManualAuto = 0 then 'Manual' ELSE 'AUTO' END as Mode, case when s.CurrentMotorOnOffStatus = 0 then   'OFF' ELSE 'ON' END as Status, case when s.CurrentMotorOnOffStatus = 0 then   'TURN ON' ELSE 'TURN OFF' END as Action from tblRemoteSensor s left join tblResource r on s.ResourceID = r.ResourceID where r.CompanyID = " + cId + "";
            var query = "";
            //query += "select r.ResourceID, r.ResourceLocation,p.ParameterID,p.ParameterName, cte.CompanyID, cte.ParameterValue, cte.InsertionDateTime, 1 as RowNum from ( select DISTINCT top(14) * from tblEnergy where ResourceID in (1068, 1069, 1070, 1071, 1072, 1073, 1074) and ParameterID in (124, 125) order by ID DESC) as cte inner join tblResource r on cte.ResourceID = r.ResourceID inner join tblParameter p on cte.ParameterID = p.ParameterID order by cte.ResourceID, cte.ParameterID select r.ResourceID, r.ResourceLocation,p.ParameterID,p.ParameterName, cte.CompanyID, cte.ParameterValue, cte.InsertionDateTime, 1 as RowNum from ( select DISTINCT top(14) * from tblEnergy where ResourceID in (1068, 1069, 1070, 1071, 1072, 1073, 1074) and ParameterID in (124, 125) order by ID DESC) as cte inner join tblResource r on cte.ResourceID = r.ResourceID inner join tblParameter p on cte.ParameterID = p.ParameterID order by cte.ResourceID, cte.ParameterID";
            query += ";with cterownumber as ( ";
            query += "select r.resourceid, r.resourcelocation,p.parameterid,p.parametername, e.companyid, e.parametervalue,   ";
            query += "row_number() over(partition by p.parameterid, r.resourceid, r.resourcelocation order by e.id desc) as rownum ";
            query += "from tblenergy e ";
            query += "inner join tblresource r on e.resourceid = r.resourceid ";
            query += "inner join tblparameter p on e.parameterid = p.parameterid ";
            query += ")   ";
            query += "select* ";
            query += "from cterownumber ";
            query += "where rownum = 1  and companyid = 4 ";
            query += "and parameterid in (124, 125) ";
            query += "order by resourceid, parameterid";
            using (var conn = new SqlConnection(System.Configuration.ConfigurationManager.ConnectionStrings["DefaultConnection"].ConnectionString))
            {
                try
                {
                    conn.Open();
                    var da = new SqlDataAdapter(query, conn);
                    var ds = new DataSet();
                    da.Fill(ds);
                    da.Fill(dt);
                }
                catch (Exception ex)
                {
                }
                finally
                {
                    conn.Close();
                }
            }
            return PartialView(dt);
        }

        public ActionResult EditMode(int? id, string mode)
        {
            int mm = 0;
            if (mode.ToLower() == "true")
            {
                mode = "False";
            }
            else
            {
                mode = "True";
            }
            string query2 = "update tblSetMode set Mode = '" + mode + "' where ResourceID = " + Convert.ToInt32(id) + "";
            using (SqlConnection conn = new SqlConnection(System.Configuration.ConfigurationManager.ConnectionStrings["DefaultConnection"].ConnectionString))
            {
                try
                {
                    conn.Open();
                    SqlCommand cmd = new SqlCommand(query2, conn);
                    cmd.ExecuteNonQuery();
                }
                catch (Exception ex)
                {
                }
            }
            if (mode == "True")
            {
                string query22 = "update tblRemoteSensor set ModeManualAuto = 1,CurrentMotorOnOffStatus = 0 where ResourceID = "+id+" "; ;
                using (SqlConnection conn = new SqlConnection(System.Configuration.ConfigurationManager.ConnectionStrings["DefaultConnection"].ConnectionString))
                {
                    try
                    {
                        conn.Open();
                        SqlCommand cmd = new SqlCommand(query22, conn);
                        cmd.ExecuteNonQuery();
                    }
                    catch (Exception ex)
                    {
                    }
                }
            }
            return RedirectToAction("SetMode");
        }

        public ActionResult Edit(int? id)
        {
            int? Mode = null;
            int? Status = null;
            string queryr = "select ID from tblRemoteSensor where ResourceID = " + id + "";
            using (SqlConnection conn = new SqlConnection(System.Configuration.ConfigurationManager.ConnectionStrings["DefaultConnection"].ConnectionString))
            {
                try
                {
                    conn.Open();
                    SqlCommand cmd = new SqlCommand(queryr, conn);
                    id = Convert.ToInt32(cmd.ExecuteScalar());
                }
                catch (Exception ex)
                {
                }
            }
            string query = "select ModeManualAuto from tblRemoteSensor where ID = " + id + "";
            using (SqlConnection conn = new SqlConnection(System.Configuration.ConfigurationManager.ConnectionStrings["DefaultConnection"].ConnectionString))
            {
                try
                {
                    conn.Open();
                    SqlCommand cmd = new SqlCommand(query, conn);
                    Mode = Convert.ToInt32(cmd.ExecuteScalar());
                }
                catch (Exception ex)
                {
                }
            }
            if (id != null && Mode != 0)
            {
                string query1 = "select CurrentMotorOnOffStatus from tblRemoteSensor where ID = " + id + "";

Views/Switch/InaugurationActivity.cshtml
<img src="~/Content/images/InaugurationSwitch.jpg" style="width:100%" />
<div style="width: 125px;
    height: 48px;
    
    position: absolute;
    top: 0;
    left: 0;
    margin: 694px 607px;" >
    <a href="/Tubewells/HMI" style="position: absolute;
    margin-top: 8px;
    font-size: 26px;
    color: #b9e530;
    font-weight: bolder;"> TURN ON </a>
</div>

Views/Switch/Index.cshtml
@model System.Data.DataTable
@using System.Data;

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<link href="~/Content/custom.css" rel="stylesheet" />
<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<script src="//code.jquery.com/ui/1.10.4/jquery-ui.js"></script>

<br />
<div class="main">
    <div class="container" style="padding: 40px; background: white;">
        <div class="row">
            <div class="span12">
                <div class="widget stacked">
                    <div class="widget-header">
                        <i class="icon-reorder"></i>
                        <h3 style="font-weight:bolder;">Remote Switch </h3>
                    </div> <!-- /widget-header -->
                    <div class="widget-content">
                        <div id="SwitchRecords">
                            <div style="float: right;">
                                <img src="~/Content/images/loading.gif" style="height: 48px;" />
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script>
    $(document).ready(function () {
        $.ajax({
            type: 'GET',
            dataType: 'html',
            url: '_SwitchRecords',
            cache: false,
            success: function (result) {
                $('#SwitchRecords').html(result);
            },
            error: function (xhr, ajaxOptions, thrownError) {
                //alert(xhr + " - " + ajaxOptions + " - " + thrownError);
                $('#SwitchRecords').html("");
            },
            async: true
        });
    });
</script>

Views/Switch/SetMode.cshtml
@model System.Data.DataTable
@using System.Data;

@{
    ViewBag.Title = "Set mode";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<link href="~/Content/custom.css" rel="stylesheet" />
<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<script src="//code.jquery.com/ui/1.10.4/jquery-ui.js"></script>

<br />
<div class="main">
    <div class="container" style="padding: 40px; background: white;">
        <div class="row">
            <div class="span12">
                <div class="widget stacked">
                    <div class="widget-header">
                            <i class="icon-reorder"></i>
                            <h3 style="font-weight:bolder;">Auto Mode Management </h3>
                        </div> <!-- /widget-header -->
                    <div class="widget-content">
                        <div id="SwitchRecords">
                            <div style="float: right;">
                                <img src="~/Content/images/loading.gif" style="height: 48px;" />
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script>
    $(document).ready(function () {
        $.ajax({
            type: 'GET',
            dataType: 'html',
            url: '_ModeRecords',
            cache: false,
            success: function (result) {
                $('#SwitchRecords').html(result);
            },
            error: function (xhr, ajaxOptions, thrownError) {
                //alert(xhr + " - " + ajaxOptions + " - " + thrownError);
                $('#SwitchRecords').html("");
            },
            async: true
        });
    });
</script>

Views/Switch/_ModeRecords.cshtml
@model System.Data.DataTable
@using System.Data;

@{
    ViewBag.Title = "";
    Layout = "";
}




<div class="col-md-12" style="padding-top: 20px !important;">
    <table class="table table-bordered table-striped table-highlight" style="color: black; font-size:11px;">
        <thead style="font-weight: bolder; text-align: center;">
            <tr>
                <td>Tubewell Location</td>
                <td>Auto Operation Mode</td>
                <td>Action</td>
            </tr>
        </thead>
        <tbody>
            @for (int i = 0; i < 7; i ++)
            {

                @*<tr>
                    <td>@Model.Rows[i][1]</td>
                    @if (Convert.ToInt32(Model.Rows[i][2]) == 0)
                    {
                        <td style=" text-align: center;">
                            Remote Control
                        </td>
                    }
                    else
                    {
                        <td style=" text-align: center;">
                            Time Scheduling
                        </td>
                    }
                    @if (Convert.ToInt32(Model.Rows[i][2]) == 0)
                    {
                    <td style=" text-align: center;">
                        @Html.ActionLink("Switch to Time Scheduling", "EditMode", new { id = Model.Rows[i][0] , mode = Model.Rows[i][2] })
                    </td>
                    }
                    else
                    {
                    <td style=" text-align: center;">
                        @Html.ActionLink("Switch to Remote Control", "EditMode", new { id = Model.Rows[i][0] , mode = Model.Rows[i][2]})
                    </td>
                    }
                </tr>*@
				<tr>
                    <td>@Model.Rows[i][1]</td>
                    @if (Convert.ToInt32(Model.Rows[i][2]) == 0)
                    {
                        <td style=" text-align: center;">
                            Time Scheduling
                        </td>
                    }
                    else
                    {
                        <td style=" text-align: center;">
                            Remote Control
                        </td>
                    }
                    @if (Convert.ToInt32(Model.Rows[i][2]) == 0)
                    {
                    <td style=" text-align: center;">
                        @Html.ActionLink("Switch to Remote Control", "EditMode", new { id = Model.Rows[i][0] , mode = Model.Rows[i][2] })
                    </td>
                    }
                    else
                    {
                    <td style=" text-align: center;">
                        @Html.ActionLink("Switch to Time Scheduling", "EditMode", new { id = Model.Rows[i][0] , mode = Model.Rows[i][2]})
                    </td>
                    }
                </tr>

            }
        </tbody>
    </table>

</div>

Views/Switch/_SwitchRecords.cshtml
@model System.Data.DataTable
@using System.Data;

@{
    ViewBag.Title = "";
    Layout = "";
}

<style>
    .modal-backdrop {
        position: static !important;
    }
</style>

<script>
    $(function () {
        $('#modalCloseOFFCross').on('click', function () {
            $('#myModal').hide();
        })
    })
</script>
<script>
    $(function () {
        $('#modalCloseOFFCancle').on('click', function () {
            $('#myModal').hide();
        })
    })
</script>
<script>
    $(function () {
        $('#modalCloseOnCross').on('click', function () {
            $('#myModalON').hide();
        })
    })
</script>
<script>
    $(function () {
        $('#modalCloseOnCancle').on('click', function () {
            $('#myModalON').hide();
        })
    })
</script>

<div class="col-md-12" style="padding: 20px !important;">
    <div class="col-md-8">
    </div>
    <div class="col-md-2 col-xs-6">
        <input class="btn btn-success" type="button" data-toggle="modal" data-target="#myModalON" value="Master ON" />
    </div>
    <div class="col-md-2 col-xs-6">
        <input class="btn btn-danger" type="button" data-toggle="modal" data-target="#myModal" value="Master OFF" />
    </div>
</div>

<div class="col-md-12" style="padding-top: 20px !important;">
    <table class="table table-bordered table-striped table-highlight" style="color: black; font-size:11px;">
        <thead style="font-weight: bolder; text-align: center;">
            <tr>
                <td>Tubewell Location</td>
                <td>Remote Mode</td>
                <td>Pump Status</td>
                <td>Action</td>
            </tr>
        </thead>
        <tbody>
            @for (int i = 0; i < 7 ; i++)
            {

                <tr>
                    <td>@Model.Rows[i][1]</td>
                    @if (Convert.ToInt32(Model.Rows[i][2]) == 0)
                    {
                        <td style=" text-align: center;">
                            OFF
                        </td>
                    }
                    else
                    {
                        <td style=" text-align: center;">
                            ON
                        </td>
                    }
                    @if (Convert.ToInt32(Model.Rows[i][3]) == 0)
                    {
                        <td style=" text-align: center;">
                            OFF
                        </td>
                    }
                    else
                    {
                        <td style=" text-align: center;">
                            ON
                        </td>
                    }
                    @if (Convert.ToInt32(Model.Rows[i][2]) == 0)
                    {
                        if (Convert.ToInt32(Model.Rows[i][3]) == 0)
                        {
                            <td style=" text-align: center; cursor: not-allowed">
                                TURN ON
                            </td>
                        }
                        else
                        {
                            <td style=" text-align: center; cursor: not-allowed">
                                TURN OFF
                            </td>
                        }
                    }
                    else
                    {
                        if (Convert.ToInt32(Model.Rows[i][3]) == 0)
                        {
                            <td style=" text-align: center;">
                                @Html.ActionLink("TURN ON", "Edit", new { id = Model.Rows[i][0] })
                            </td>
                        }
                        else
                        {
                            <td style=" text-align: center;">
                                @Html.ActionLink("TURN OFF", "Edit", new { id = Model.Rows[i][0] })
                            </td>
                        }
                    }
                </tr>

            }
        </tbody>
    </table>

</div>

<div class="modal" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" id="modalCloseOFFCross" class="close" data-dismiss="#myModal" aria-hidden="true">&times;</button>
                <h4 class="modal-title" id="myModalLabel">Warning !!</h4>
            </div>
            <div class="modal-body">
                Are you sure you want to SWITCH OFF all tubewells ?
            </div>
            <div class="modal-footer">
                @using (Html.BeginForm("MasterOff", "Switch"))
                {
                    @Html.AntiForgeryToken()
                    <button type="button" id="modalCloseOFFCancle" class="btn btn-default" data-dismiss="#myModal">Cancel</button>
                    <button type="submit" class="btn btn-warning">Confirm</button>
                }
            </div>
        </div>
    </div>
</div>

<div class="modal" id="myModalON" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" id="modalCloseOnCross" class="close" data-dismiss="#myModalON" aria-hidden="true">&times;</button>
                <h4 class="modal-title" id="myModalLabel">Warning !!</h4>
            </div>
            <div class="modal-body">
                Are you sure you want to SWITCH ON all tubewells ?
            </div>
            <div class="modal-footer">
                @using (Html.BeginForm("MasterOn", "Switch"))
                {
                    @Html.AntiForgeryToken()
                    <button type="button" class="btn btn-default" id="modalCloseOnCancle" data-dismiss="#myModalON">Cancel</button>
                    <button type="submit" class="btn btn-warning">Confirm</button>
                }
            </div>
        </div>
    </div>
</div>

Views/Switch/_SwitchRecords2.cshtml
@model System.Data.DataTable
@using System.Data;

@{
    ViewBag.Title = "";
    Layout = "";
}

<style>
    .modal-backdrop {
        position: static !important;
    }
</style>

<script>
    $(function () {
        $('#modalCloseOFFCross').on('click', function () {
            $('#myModal').hide();
        })
    })
</script>
<script>
    $(function () {
        $('#modalCloseOFFCancle').on('click', function () {
            $('#myModal').hide();
        })
    })
</script>
<script>
    $(function () {
        $('#modalCloseOnCross').on('click', function () {
            $('#myModalON').hide();
        })
    })
</script>
<script>
    $(function () {
        $('#modalCloseOnCancle').on('click', function () {
            $('#myModalON').hide();
        })
    })
</script>

<div class="col-md-12" style="padding: 20px !important;">
    <div class="col-md-8">
    </div>
    <div class="col-md-2 col-xs-6">
        <input class="btn btn-success" type="button" data-toggle="modal" data-target="#myModalON" value="Master ON" />
    </div>
    <div class="col-md-2 col-xs-6">
        <input class="btn btn-danger" type="button" data-toggle="modal" data-target="#myModal" value="Master OFF" />
    </div>
</div>

<div class="col-md-12" style="padding-top: 20px !important;">
    <table class="table table-bordered table-striped table-highlight" style="color: black; font-size:11px;">
        <thead style="font-weight: bolder; text-align: center;">
            <tr>
                <td>Tubewell Location</td>
                <td>Remote Mode</td>
                <td>Pump Status</td>
                <td>Action</td>
            </tr>
        </thead>
        <tbody>
            @for (int i = 0; i < 14 ; i+=2)
            {

                <tr>
                    <td>@Model.Rows[i][1]</td>
                    @if (Convert.ToInt32(Model.Rows[i][5]) == 0)
                    {
                        <td style=" text-align: center;">
                            OFF
                        </td>
                    }
                    else
                    {
                        <td style=" text-align: center;">
                            ON
                        </td>
                    }
                    @if (Convert.ToInt32(Model.Rows[i+1][5]) == 0)
                    {
                        <td style=" text-align: center;">
                            OFF
                        </td>
                    }
                    else
                    {
                        <td style=" text-align: center;">
                            ON
                        </td>
                    }
                    @if (Convert.ToInt32(Model.Rows[i][5]) == 0)
                    {
                        if (Convert.ToInt32(Model.Rows[i+1][5]) == 0)
                        {
                            <td style=" text-align: center; cursor: not-allowed">
                                TURN ON
                            </td>
                        }
                        else
                        {
                            <td style=" text-align: center; cursor: not-allowed">
                                TURN OFF
                            </td>
                        }
                    }
                    else
                    {
                        if (Convert.ToInt32(Model.Rows[i+1][5]) == 0)
                        {
                            <td style=" text-align: center;">
                                @Html.ActionLink("TURN ON", "Edit", new { id = Model.Rows[i+1][0] })
                            </td>
                        }
                        else
                        {
                            <td style=" text-align: center;">
                                @Html.ActionLink("TURN OFF", "Edit", new { id = Model.Rows[i+1][0] })
                            </td>
                        }
                    }
                </tr>

            }
            @*@foreach (DataRow row in Model.Rows)
        {
            if (row["Resource"].ToString() == "ShokatKhanamWell1" || row["Resource"].ToString() == "ShokatKhanamWell2")
            {

            }
            else
            {
                <tr>
                    <td> @row["Resource"]</td>
                    @if (row["Mode"].ToString() == "Manual")
                    {
                        <td style=" text-align: center;">
                            AUTO
                        </td>
                    }
                    else if (row["Mode"].ToString() == "AUTO")
                    {
                        <td style=" text-align: center;">
                            Manual
                        </td>
                    }
                    <td style=" text-align: center;"> @row["Status"]</td>
                    @if (row["Mode"].ToString() == "AUTO")
                    {
                        <td style=" text-align: center; cursor: not-allowed">
                            @row["Action"].ToString()
                        </td>
                    }
                    else
                    {
                        <td style=" text-align: center;">
                            @Html.ActionLink(row["Action"].ToString(), "Edit", new { id = row["ID"] })
                        </td>
                    }
                </tr>
            }
        }*@
        </tbody>
    </table>

</div>

<div class="modal" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" id="modalCloseOFFCross" class="close" data-dismiss="#myModal" aria-hidden="true">&times;</button>
                <h4 class="modal-title" id="myModalLabel">Warning !!</h4>
            </div>
            <div class="modal-body">
                Are you sure you want to SWITCH OFF all tubewells ?
            </div>
            <div class="modal-footer">
                @using (Html.BeginForm("MasterOff", "Switch"))
                {
                    @Html.AntiForgeryToken()
                    <button type="button" id="modalCloseOFFCancle" class="btn btn-default" data-dismiss="#myModal">Cancel</button>
                    <button type="submit" class="btn btn-warning">Confirm</button>
                }
            </div>
        </div>
    </div>
</div>

<div class="modal" id="myModalON" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" id="modalCloseOnCross" class="close" data-dismiss="#myModalON" aria-hidden="true">&times;</button>
                <h4 class="modal-title" id="myModalLabel">Warning !!</h4>
            </div>
            <div class="modal-body">
                Are you sure you want to SWITCH ON all tubewells ?
            </div>
            <div class="modal-footer">
                @using (Html.BeginForm("MasterOn", "Switch"))
                {
                    @Html.AntiForgeryToken()
                    <button type="button" class="btn btn-default" id="modalCloseOnCancle" data-dismiss="#myModalON">Cancel</button>
                    <button type="submit" class="btn btn-warning">Confirm</button>
                }
            </div>
        </div>
    </div>
</div>