Controllers/TubewellsController.cs
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.Diagnostics;
using System.Dynamic;
using System.Globalization;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;
using WASA_EMS.Models;

namespace WASA_EMS.Controllers
{

    public class TubewellsController : Controller
    {
        // GET: Tubewells
        public ActionResult Home()
        {
            return View();
        }
        public ActionResult Dashboard()
        {
            return View();
        }

        public ActionResult ParameterizedData()
        {
            WASA_EMS_Entities db = new WASA_EMS_Entities();
            IList<string> parameterList = new List<string>();
            IList<string> resourceList = new List<string>();
            string paramsListQuery = "select p.ParameterDescription from tblParameter p inner join tblTemplateParameter tp on tp.ParameterID = p.ParameterID where tp.TemplateID = 64 order by p.paramOrder";
            using (SqlConnection conn = new SqlConnection(System.Configuration.ConfigurationManager.ConnectionStrings["DefaultConnection"].ConnectionString))
            {
                try
                {
                    DataTable dtParams = new DataTable();
                    conn.Open();
                    SqlDataAdapter sdaParams = new SqlDataAdapter(paramsListQuery, conn);
                    sdaParams.Fill(dtParams);
                    foreach (DataRow dr in dtParams.Rows)
                    {
                        parameterList.Add(dr["ParameterDescription"].ToString());
                    }
                }
                catch (Exception ex)
                {

                }
            }
            foreach (var item in db.tblResources.AsEnumerable().Where(item => item.CompanyID == 4 && item.TemplateID == 64))
            {
                resourceList.Add(item.ResourceLocation);
            }
            ResourceAndParameterSelector rs = new ResourceAndParameterSelector();
            rs.resourceID = "C-II Block Johar Town";
            rs.parameterID = "Pump Status";
            rs.dateFrom = "";
            rs.timeFrom = "";
            rs.dateTo = "";
            rs.timeTo = "";
            ViewBag.ResourceList = resourceList;
            ViewBag.ParameterList = parameterList;
            return View(rs);
        }

        [HttpPost]
        public ActionResult ParameterizedData(FormCollection review)
        {
            string resource = review["resource"].ToString();
            string Parameter = review["parameter"].ToString();
            DateTime dateFrom = DateTime.Parse(review["dateFrom"].ToString());
            DateTime dateTo = DateTime.Parse(review["dateTo"].ToString());
            string df_date = dateFrom.ToString("d");
            string dt_date = dateTo.ToString("d");
            string TF = review["timeFrom"];
            string TT = review["timeTo"];
            string abc = review["timeFrom"];
            string[] abc1 = abc.Split(',');
            string a = abc1[0];
            if (abc1.Length > 1)
            {
                TF = abc1[1];
            }
            else
            {
                TF = abc1[0];
            }
            DataTable dt121 = new DataTable();
            Session["TimeFrom"] = TF;
            DateTime timeFrom = DateTime.Parse(TF);
            string cba = review["timeTo"];
            string[] cba1 = cba.Split(',');
            TT = cba1[0];
            DateTime timeTo = DateTime.Parse(TT);
            string tf_time = timeFrom.ToString("t");
            string tt_time = timeTo.ToString("t");
            if (tt_time == "12:00 AM" || tt_time == "11:59 PM")
            {
                tt_time = "11:59:59 PM";
            }
            DateTime FinalTimeFrom = Convert.ToDateTime(df_date + " " + tf_time);
            DateTime FinalTimeTo = Convert.ToDateTime(dt_date + " " + tt_time);
            int c_id = Convert.ToInt32(Session["CompanyID"]);
            WASA_EMS_Entities db = new WASA_EMS_Entities();
            IList<string> parameterList = new List<string>();
            IList<string> resourceList = new List<string>();
            string paramsListQuery = "select p.ParameterDescription from tblParameter p inner join tblTemplateParameter tp on tp.ParameterID = p.ParameterID where tp.TemplateID = 64 order by p.paramOrder";
            using (SqlConnection conn = new SqlConnection(System.Configuration.ConfigurationManager.ConnectionStrings["DefaultConnection"].ConnectionString))
            {
                try
                {
                    DataTable dtParams = new DataTable();
                    conn.Open();
                    SqlDataAdapter sdaParams = new SqlDataAdapter(paramsListQuery, conn);
                    sdaParams.Fill(dtParams);
                    foreach (DataRow dr in dtParams.Rows)
                    {
                        parameterList.Add(dr["ParameterDescription"].ToString());
                    }
                }
                catch (Exception ex)
                {

                }
            }
            foreach (var item in db.tblResources.AsEnumerable().Where(item => item.CompanyID == 4 && item.TemplateID == 64))
            {
                resourceList.Add(item.ResourceLocation);
            }
            ViewBag.ResourceList = resourceList;
            ViewBag.ParameterList = parameterList;
            ViewBag.SelectedResource = resource;
            ViewBag.SelectedParameter = Parameter;
            ViewBag.SelectedTimeFrom = TF;
            ViewBag.SelectedTimeTo = TT;
            ViewBag.SelectedTimeFrom = TF.ToString();
            ViewBag.SelectedTimeTo = TT.ToString();
            ViewBag.timeFrom = TF;
            ViewBag.timeTo = TT;
            ViewBag.dateFrom = df_date;
            ViewBag.dateTo = dt_date;
            ResourceAndParameterSelector rs = new ResourceAndParameterSelector();
            rs.resourceID = resource;
            rs.parameterID = Parameter;
            rs.dateFrom = dateFrom.ToString();
            rs.timeFrom = TF;
            rs.dateTo = dateTo.ToString();
            rs.timeTo = TT;
            return View(rs);
        }
        [HttpGet]
        [OutputCache(NoStore = true, Location = System.Web.UI.OutputCacheLocation.Client, Duration = 20)]
        public PartialViewResult _ParameterizedDataView(string resources, string parameter, string datFrom, string timFrom, string datTo, string timTo)
        {
            DateTime FinalTimeFrom = DateTime.Now;
            DateTime FinalTimeTo = DateTime.Now;

            DataTable dtVal = new DataTable();
            string parameterName = "";
            if (datFrom == "" && timFrom == "" && datTo == "" && timTo == "")
            {
                FinalTimeFrom = DateTime.Now.AddHours(0).Date;
                FinalTimeTo = DateTime.Now.AddHours(0).AddDays(1).Date.AddSeconds(-1);
            }
            else
            {
                DateTime dateFrom = DateTime.Parse(datFrom);
                DateTime dateTo = DateTime.Parse(datTo);
                string df_date = dateFrom.ToString("d");
                string dt_date = dateTo.ToString("d");
                string TF = timFrom;
                string TT = timTo;
                string abc = timFrom;
                string[] abc1 = abc.Split(',');
                string a = abc1[0];
                if (abc1.Length > 1)
                {
                    TF = abc1[1];
                }
                else
                {
                    TF = abc1[0];
                }
                DataTable dt121 = new DataTable();
                Session["TimeFrom"] = TF;
                DateTime timeFrom = DateTime.Parse(TF);
                string cba = timTo;
                string[] cba1 = cba.Split(',');
                TT = cba1[0];
                DateTime timeTo = DateTime.Parse(TT);
                string tf_time = timeFrom.ToString("t");
                string tt_time = timeTo.ToString("t");
                if (tt_time == "12:00 AM" || tt_time == "11:59 PM" || tt_time == "12:00 am" || tt_time == "11:59 pm")
                {
                    tt_time = "11:59:59 PM";
                }
                FinalTimeFrom = Convert.ToDateTime(df_date + " " + tf_time);
                FinalTimeTo = Convert.ToDateTime(dt_date + " " + tt_time);
            }
            DataTable dtRes = new DataTable();
            DataTable Dashdt = new DataTable();
            var tubewellDataList = new List<TubewellParameterChartClass>();

            ////////////////////////////////////////////////////////////////////////

            string scriptString = "";
            using (SqlConnection conn = new SqlConnection(System.Configuration.ConfigurationManager.ConnectionStrings["DefaultConnection"].ConnectionString))
            {
                try
                {
                    string getResFromTemp = "select ParameterID, ParameterName from tblParameter where ParameterDescription = '" + parameter + "'";
                    SqlDataAdapter sdaRes = new SqlDataAdapter(getResFromTemp, conn);
                    DataTable dtRes1 = new DataTable();
                    sdaRes.Fill(dtRes1);
                    int ite = 0;
                    foreach (DataRow drRes in dtRes1.Rows)
                    {
                        parameterName = drRes["ParameterName"].ToString();
                        ite += 1;
                        string getParamsFromRes = "";
                        getParamsFromRes = "select r.ResourceID, r.ResourceName from tblResource r where r.ResourceName = '" + resources + "' ";
                        SqlDataAdapter sdaPar = new SqlDataAdapter(getParamsFromRes, conn);
                        DataTable dtPar = new DataTable();
                        sdaPar.Fill(dtPar);
                        scriptString += "var chart" + ite + " = new CanvasJS.Chart(\"chartContainer" + ite + "\", {";

Views/Tubewells/Dashboard.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<link href="~/Content/custom.css" rel="stylesheet" />
<iframe width="100%" height="800px" src="https://app.powerbi.com/view?r=eyJrIjoiNTE1MWNiZmUtNGQwZS00MzJmLThlZmYtNDNjNWQ0MThjMjIwIiwidCI6Ijc1ZGYwOTZjLThiNzItNDhlNC05YjkxLWNiZjc5ZDg3ZWUzYSIsImMiOjl9" frameborder="0" allowFullScreen="true"></iframe>

Views/Tubewells/HMI.cshtml
@model ResourceSellector
@{
    ViewBag.Title = "Dashboard";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<link href="~/Content/custom.css" rel="stylesheet" />
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/dt/dt-1.10.18/datatables.min.css" />
<link href="~/Content/animationTubeWell.css" rel="stylesheet" />
<link href="~/Content/chosen.css" rel="stylesheet" />
<link href="~/Content/Site.css" rel="stylesheet" />
@*<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<script src="//code.jquery.com/ui/1.10.4/jquery-ui.js" type="text/javascript"></script>
<script type="text/javascript" src="~/Metronic/assets/global/scripts/datatable.js"></script>
<script type="text/javascript" src="~/Metronic/assets/global/plugins/datatables/datatables.min.js"></script>
<script src="~/Scripts/chosen.jquery.min.js"></script>*@
<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<script src="//code.jquery.com/ui/1.10.4/jquery-ui.js" type="text/javascript"></script>
<script type="text/javascript">
    $(document).ready(function () {
        var table = $('#example').DataTable({
        });
        $("#resourceType").change(function () {
            var model = $('#resource');
            //alert("Hello Called");
            //alert($("#resourceType :selected").val());
            model.empty();
            $.getJSON('/Home/IndexChanged', { value: $("#resourceType :selected").val() }, function (data) {
                for (var i = 0; i < data.resource.length; i++) {
                    model.append("<option value=" + data.resource[i] + ">" + data.resource[i] + "</option>")
                }
                //alert(data.resource);
                //alert("called");
            })

            var model1 = $('#parameter');

            model1.empty();
            $.getJSON('/Home/ParameterIndexChanged', { value: $("#resourceType :selected").val() }, function (data) {
                for (var i = 0; i < data.parameter.length; i++) {
                    model1.append("<option value=" + data.parameter[i] + ">" + data.parameter[i] + "</option>")
                }
                //alert(data.parameter);
            })
                .error(function () {
                    alert("replace operation failed");
                });
            return false;
        });
        $(".chosen").chosen();
    });
</script>
<script type="text/javascript">
    //alert('@Model.resourceName.ToString()');
    //console.log('PI: ' +(@Model.resourceName));
    var resN = '@Model.resourceName';
    var resT = '@Model.resourceType';
    $(document).ready(function () {
        $.ajax({
            type: 'GET',
            dataType: 'html',
            url: '_HMIView',
            cache: false,
            data: { resourceName: resN , resourceType: resT },
            success: function (result) {
                $('#DashboardDiagram').html(result);
            },
            error: function (xhr, ajaxOptions, thrownError) {
                $('#DashboardDiagram').html("");
            },
            async: true
        });
    });
    //var refreshId = setInterval(function () {
    //    var properID = $('#DashboardDiagram').load('_DashboardView');
    //    if (properID > 0) {
    //        clearInterval(refreshId);
    //    }
    //}, 10000);
</script>

<div class="container">
        
        <div class="row">
            @using (Html.BeginForm("HMI", "Tubewells"))
            {
                <div class="span12">

                    <div class="widget stacked" style="margin-top:20px;">
                        <div class="widget-content">
                            <div class="container">
                                <div class="row">
                                    <div class="col-md-12" style="padding: 10px;margin-top: 20px;">
                                        <center>
                                            @using (Html.BeginForm("HMI", "Tubewells"))
                                            {
                                                if (ViewBag.SelectedResource != null)
                                                {
                                                    <div class="col-md-3 col-md-offset-3">@Html.DropDownList("resource", new SelectList(ViewBag.ResourceList, ViewBag.SelectedResource), new { @class = "form-control chosen", @style = "width:100%; height:34px; color:black;" })</div>
                                                }
                                                else
                                                {
                                                    <div class="col-md-3 col-md-offset-3">
                                                        @Html.DropDownList("resource", new SelectList(ViewBag.ResourceList), new { @class = "form-control chosen", @style = "width:100%; height:34px; color:black;" })
                                                    </div>
                                                }
                                                <div class="col-md-2">
                                                    <button type="submit" class="btn btn-info" style="width:100%; height:34px !important">
                                                        Update
                                                    </button>
                                                </div>
                                            }
                                        </center>
                                    </div>
                                    <div id="DashboardDiagram" style="min-height: 1000px !important;    background-color: white !important;">
                                        <div style="float: right;">
                                            <img src="~/Content/images/loading.gif" style="height: 48px;" />
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div> <!-- /widget-content -->
                    </div> <!-- /widget -->

                </div>
            <!-- /span12 -->
            }


        </div> <!-- /row -->

    </div>

Views/Tubewells/Home.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Home</title>
</head>
<body>
    <div> 
    </div>
</body>
</html>

Views/Tubewells/ParameterWiseReport.cshtml
@{
    ViewBag.Title = "Parameter Report";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!DOCTYPE html>

<link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
<link href="~/Content/custom.css" rel="stylesheet" />
<link href="~/Content/datatables.min.css" rel="stylesheet" />
<link href="~/Metronic/assets/global/plugins/bootstrap/css/bootstrap.min.css" rel="stylesheet" />
<script src="~/Scripts/jquery.min.js"></script>

<script src="~/Scripts/jquery-ui.js"></script>


<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.13.1/css/bootstrap-select.css" />
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.bundle.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.13.1/js/bootstrap-select.min.js"></script>

<div class="row">
    <div class="col-lg-12 col-xs-12 col-sm-12" style="z-index:-1">
        <div class="portlet light ">
            <div class="portlet-body">


                <!-- DataTable Row -->

                <div class="row">
                    <div class="col-md-12">
                        <!-- BEGIN EXAMPLE TABLE PORTLET-->
                        <div class="portlet light bordered">
                            <div class="portlet-title">
                                <div class="caption font-dark">
                                    <i class="icon-docs font-dark"></i>
                                    <span class="caption-subject bold uppercase">PARAMETER WISE REPORT</span>
                                </div>
                                <div class="tools"> </div>
                            </div>
                            <div class="portlet-body">
                                <div id="StatusReportDiv">

                                    <div style="float: right;">
                                        <img src="~/Content/images/loading.gif" style="height: 48px;" />
                                    </div>
                                </div>


                            </div>
                        </div>
                        <!-- END EXAMPLE TABLE PORTLET-->
                    </div>
                </div>
            </div>
        </div>

        <!-- Left and right controls -->
        @*<a class="left carousel-control" href="#myCarousel" data-slide="prev">
                <span class="glyphicon glyphicon-chevron-left"></span>
                <span class="sr-only">Previous</span>
            </a>
            <a class="right carousel-control" href="#myCarousel" data-slide="next">
                <span class="glyphicon glyphicon-chevron-right"></span>
                <span class="sr-only">Next</span>
            </a>*@

    </div>
</div>

@*<script src="~/Scripts/jquery.min.js"></script>
<script src="~/Scripts/jquery-ui.js"></script>
<script type="text/javascript" src="~/Metronic/assets/global/scripts/datatable.js"></script>
<script type="text/javascript" src="~/Metronic/assets/global/plugins/datatables/datatables.min.js"></script>*@
<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<script type="text/javascript" src="https://cdn.datatables.net/1.10.22/js/jquery.dataTables.min.js"></script>
<script type="text/javascript">
    $(document).ready(function () {
        var table = $('#example').DataTable({
        });
    });
</script>
<script type="text/javascript">
    getStatusResults();
    window.onload = function () {
        //alert('on load');
        var refreshId = setInterval(function () {
            var properID = getStatusResults();
            if (properID > 0) {
                clearInterval(refreshId);
            }
        }, 20000);
    }

    function getStatusResults() {
        $.ajax({
            type: 'GET',
            dataType: 'html',
            url: '_ParameterReportView',
            cache: false,
            success: function (result) {
                $('#StatusReportDiv').html(result);
            },
            error: function (xhr, ajaxOptions, thrownError) {
                $('#StatusReportDiv').html("");
            },
            async: true
        });
    }
</script>

Views/Tubewells/_StatusReportView.cshtml
@using System.Data;
@using System.Data.SqlClient;
@using Newtonsoft.Json;
@model IEnumerable<TubewellDataClass>

<link href="~/Content/datatables.min.css" rel="stylesheet" type="text/css" />
<link href="~/Content/buttons.dataTables.min.css" rel="stylesheet" type="text/css" />

@*<script src="https://code.jquery.com/jquery-3.5.1.min.js" type="text/javascript"></script>*@

<script src="~/Metronic/assets/global/scripts/jquery.dataTables.min.js"></script>


<script src="~/Metronic/assets/global/scripts/dataTables.buttons.min.js" type="text/javascript"></script>
<script src="~/Metronic/assets/global/scripts/buttons.print.min.js" type="text/javascript"></script>
<script src="~/Metronic/assets/global/scripts/buttons.html5.min.js" type="text/javascript"></script>
@*<script src="~/Metronic/assets/global/scripts/pdfmake.min.js" type="text/javascript"></script>*@
<script src="~/Metronic/assets/global/scripts/vfs_fonts.js" type="text/javascript"></script>
<script src="~/Metronic/assets/global/scripts/jszip.min.js" type="text/javascript"></script>
<script src="https://canvasjs.com/assets/script/canvasjs.min.js"></script>

<script type="text/javascript">
    $(document).ready(function () {
        @Html.Raw(ViewData["chartData"])
        chart1.render();
        function toogleDataSeries(e) {
            if (typeof (e.dataSeries.visible) === "undefined" || e.dataSeries.visible) {
                e.dataSeries.visible = false;
            } else {
                e.dataSeries.visible = true;
            }
            chart1.render();
        }
        if (!$.fn.DataTable.isDataTable('#tubeWellTable')) {
            var table = $('#tubeWellTable').DataTable({
                "scrollX": true,
                "paging": false,
                "ordering": false,
                "info": false,
                "columnDefs": [
                    { "className": "dt-center", "targets": "_all" }
                ],
                dom: 'Bfrtip',
                //buttons: [
                //    'copy', 'csv', 'excel', 'pdf', 'print'
                //]
                buttons: [
					'print', 'csv',
                    {
                        extend: 'excelHtml5',
                        title: '@Session["ReportTitle"]'
                    },
                    {
                        extend: 'pdfHtml5',
                        title: '@Session["ReportTitle"]'
                    }
                ]
            });
            //$('#tubeWellTable tbody').on('click', 'td:nth-child(1)', function () {
            $('#tubeWellTable tbody').on('click', 'td.locationName', function () {
                
                var resr = table.row(this).data()[0];
                console.log(resr);
                $.post('/Tubewells/SetVariable',
                    { key: "TheResource", value: resr }, function (data) {
                    });
                $.ajax({
                    url : '@Url.Action("HMI","Tubewells")',
                    cache: false,
                    data: resr,
                    success: function (result) {
                        window.location = "/Tubewells/HMI";
                    },
                    error: function (xhr, ajaxOptions, thrownError) {
                    },
                    async: false
                });
            });
        }
    });
</script>
<div class="portlet-title">
    <div class="row" style="opacity:0.9">
        <div class="portlet-body">
            <div class="widget stacked">
                <div class="widget-content">
                    <div>
                        <center>
                            <div id="chartContainer1" style="width: 95%; height: 500px"></div>
                        </center>
                    </div>
                </div>
            </div>
        </div>
    </div>

</div>

<hr style="margin-top: 1rem; margin-bottom: 1rem; border: 0; border-top: 1px solid rgba(0, 0, 0, 0.1);" />

<div class="row" style="opacity:0.9">
    <div class="portlet-body">
        <div class="widget stacked" style="margin-top:70px; ">
            <div class="widget-content">
                <div>
                    <center>


                        <table id="tubeWellTable" class="display" style="width:100%">
                            <thead>
                                <tr style="background-color: #a8c9cd;">
                                    <th>Name of Location</th>
                                    <th>Pump Status</th>
                                    <th>Total Working Hours</th>
                                    <th>Manual Mode</th>
                                    <th>Remote Mode</th>
                                    <th>Scheduling Mode</th>
                                    <th>Chlorine Level</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model)
                                {
                                <tr>
                                    <td class="locationName" style="cursor:pointer; color: cornflowerblue; text-align:left !important; text-decoration:underline">@item.locationName</td>
                                    @if (item.pumpStatus.Count == 0)
                                    {
                                        <td>Inactive</td>
                                        <td>-</td>
                                        <td>-</td>
                                        <td>-</td>
                                        <td>-</td>
                                        <td>-</td>
                                    }
                                    else
                                    {
                                        if (item.pumpStatus.FirstOrDefault() == 0)
                                        {
                                            <td>OFF</td>
                                        }
                                        else
                                        {
                                            <td>ON</td>
                                        }
                                        <td>@item.workingHoursToday</td>
                                        if (item.schedulingStatus.FirstOrDefault() == 1)
                                        {
                                            <td>OFF</td>
                                            <td>OFF</td>
                                            <td>ON</td>
                                        }
                                        else if (item.remoteControll.FirstOrDefault() == 1)
                                        {
                                            <td>OFF</td>
                                            <td>ON</td>
                                            <td>OFF</td>
                                        }
                                        else if (item.manualStatus.FirstOrDefault() == 1)
                                        {
                                            <td>ON</td>
                                            <td>OFF</td>
                                            <td>OFF</td>
                                        }
                                        else
                                        {
                                            <td>OFF</td>
                                            <td>OFF</td>
                                            <td>OFF</td>
                                        }
                                        if (item.chlorineLevel.FirstOrDefault() == 0)
                                        {
                                            <td>HALF</td>
                                        }
                                        else
                                        {
                                            <td>FULL</td>
                                        }
                                    }
                                </tr>
                                }
                            </tbody>
                        </table>


                    </center>
                </div>
            </div>
        </div>
    </div>
</div>